apiVersion: v1
kind: Secret
metadata:
  name: {{ include "demokotlin.fullname" . }}-{{ .Release.Revision }}
stringData:
  DB_PASSWORD: {{ .Values.mysql.auth.rootPassword | quote }}
  DB_HOST: {{ .Release.Name }}-mysql:3306